# Tugas Wrangling 2

* Silakan download dan kerjakan soal berikut dimanapun (laptop pribadi/google colab/etc.)
* Setelah selesai mengerjakan, upload file ini di tempat yang telah disediakan pada platform.
* Beri nama file seperti berikut: {username}-wrangling-2.ipynb
* Contoh: johndoe-ab12-wrangling-2.ipynb
* Tutorial: https://discourse.pacmann.ai/t/pengumuman-seluruh-platform-pacmann-ai/409
* Username dapat dilihat di dalam akun anda.
* Mohon jangan mengubah nama variabel yang telah diberikan.
* Namun anda diperbolehkan untuk menambah variabel apapun.
---

In [2]:
import numpy as np
import pandas as pd

1. Diberikan data sebagai berikut `a = np.array([3,3,6,1,8,3,9,5,7])`. Tanpa menggunakan `np.mean()` hitunglah nilai mean dari data a tersebut.
hint:

$$ \mu = \frac{\sum_{i=1}^n x_i}{n} $$

In [2]:
a = np.array([3,3,6,1,8,3,9,5,7])
mean_a = sum(a)/len(a)
print(mean_a)

5.0


2. Jika kita memiliki array `X`, kita dapat melakukan teknik yang dinamakan _centering_. Untuk melakukan _centering_ dilakukan langkah sebagai berikut.
- Hitung nilai _mean_ untuk tiap-tiap kolom.
- Untuk tiap baris pada kolom, kurangi nilai tiap elemen dengan kolom yang berkorespondensi:
$$ A = \begin{bmatrix} a_{11}&a_{12} \\ a_{21}&a_{22} \end{bmatrix} $$

$$ \mu_A = [\mu_1 \quad \mu_2]$$

$$ A_{centered} = \begin{bmatrix} a_{11} - \mu_1 &a_{12} - \mu_2 \\ a_{21} - \mu_1 &a_{22}-\mu_2 \end{bmatrix} $$

- Untuk mengecek apakah hasilnya benar atau tidak, anda tampilkan nilai mean dari masing-masing kolom untuk `A_centered`.
- Hasil dapat dianggap benar jika nilai dari `A_centered` adalah 0 atau mendekati 0.  

In [3]:
a = np.array([[1,3,4],[2,8,5],[5,9,2],[7,1,2]])
# your code here
mean_col = np.mean(a, axis=0)
a_centered = a - mean_col
print(a_centered.mean(0))

[0. 0. 0.]


3. Diberikan array sebagai berikut:

`b = np.array([1,6,2,7,9,2,6,3,9,2,11,4,9,2,5,1,4,8,2,6,5,13,14,17,1,11,2,14,4])`

Hitunglah ada berapa angka yang bernilai $\leq5$

In [4]:
b = np.array([1,6,2,7,9,2,6,3,9,2,11,4,9,2,5,1,4,8,2,6,5,13,14,17,1,11,2,14,4])#
n = len(b[b<=5]) # your code here
print('jumlah angka yang bernilai <= 5 ada:', n)

jumlah angka yang bernilai <= 5 ada: 15


4. Diberikan array sebagai berikut:

`b = np.array([[5, 0, 3, 3],[7, 9, 3, 5],[2, 4, 7, 6],[4, 3, 3, 9],[3, 5, 7, 2]])`

ambillah nilai array yang kurang dari 5. Expected output:`[0,3,3,3,2,4,4,3,3,3,2]`

In [5]:
b = np.array([[5, 0, 3, 3],[7, 9, 3, 5],[2, 4, 7, 6],[4, 3, 3, 9],[3, 5, 7, 2]])
print(b[b<5])

[0 3 3 3 2 4 4 3 3 3 2]


5. Dari folder `data_tugas2` baca data `football.csv` di dalam pandas, parse kolom yang berupa tanggal dan jadikan kolom tersebut index dan tampilkan tabelnya. Lalu save data yang telah diolah kedalam variabel `dataframe_1` dan tulis file `football.xlsx`.

In [6]:
dataframe_1 = pd.read_csv('data_tugas2/football.csv', parse_dates=[1])
dataframe_1.to_excel('football.xlsx')
dataframe_1.head()

Div       Date        HomeTeam    AwayTeam  FTHG  FTAG FTR  HTHG  HTAG HTR  \
0  E0 2016-08-13         Burnley     Swansea     0     1   A     0     0   D   
1  E0 2016-08-13  Crystal Palace   West Brom     0     1   A     0     0   D   
2  E0 2016-08-13         Everton   Tottenham     1     1   D     1     0   H   
3  E0 2016-08-13            Hull   Leicester     2     1   H     1     0   H   
4  E0 2016-08-13        Man City  Sunderland     2     1   H     1     0   H   

   ... BbAv<2.5  BbAH  BbAHh  BbMxAHH  BbAvAHH  BbMxAHA  BbAvAHA  PSCH  PSCD  \
0  ...     1.61    32  -0.25     2.13     2.06     1.86     1.81  2.79  3.16   
1  ...     1.52    33  -0.50     2.07     2.00     1.90     1.85  2.25  3.15   
2  ...     1.77    32   0.25     1.91     1.85     2.09     2.00  3.64  3.54   
3  ...     1.67    31   0.25     2.35     2.26     2.03     1.67  4.68  3.50   
4  ...     2.48    34  -1.50     1.81     1.73     2.20     2.14  1.25  6.50   

    PSCA  
0   2.89  
1   3.86  
2   2.16  
3   1.92  
4  14.50  

[5 rows x 65 columns]

6. Dari folder `data_tugas2` baca data `avocado.json` di dalam pandas dan simpan dataframe kedalam `dataframe_2` lalu tampilkan tabelnya. Kemudian save kedalam `avocado.csv`.
> note: orientasi json bukan default, perhatikan terlebih dahulu lalu sesuaikan.

In [3]:
dataframe_2 = pd.read_json('data_tugas2/avocado.json', orient='split')
dataframe_2
dataframe_2.to_csv('avocado.csv')

Unnamed: 0       Date  AveragePrice  Total Volume     4046       4225  \
0               0 2015-12-27          1.33      64236.62  1036.74   54454.85   
1               1 2015-12-20          1.35      54876.98   674.28   44638.81   
2               2 2015-12-13          0.93     118220.22   794.70  109149.67   
3               3 2015-12-06          1.08      78992.15  1132.00   71976.41   
4               4 2015-11-29          1.28      51039.60   941.48   43838.39   
...           ...        ...           ...           ...      ...        ...   
18244           7 2018-02-04          1.63      17074.83  2046.96    1529.20   
18245           8 2018-01-28          1.71      13888.04  1191.70    3431.50   
18246           9 2018-01-21          1.87      13766.76  1191.92    2452.79   
18247          10 2018-01-14          1.93      16205.22  1527.63    2981.04   
18248          11 2018-01-07          1.62      17489.58  2894.77    2356.13   

         4770  Total Bags  Small Bags  Large Bags  XLarge Bags          type  \
0       48.16     8696.87     8603.62       93.25          0.0  conventional   
1       58.33     9505.56     9408.07       97.49          0.0  conventional   
2      130.50     8145.35     8042.21      103.14          0.0  conventional   
3       72.58     5811.16     5677.40      133.76          0.0  conventional   
4       75.78     6183.95     5986.26      197.69          0.0  conventional   
...       ...         ...         ...         ...          ...           ...   
18244    0.00    13498.67    13066.82      431.85          0.0       organic   
18245    0.00     9264.84     8940.04      324.80          0.0       organic   
18246  727.94     9394.11     9351.80       42.31          0.0       organic   
18247  727.01    10969.54    10919.54       50.00          0.0       organic   
18248  224.53    12014.15    11988.14       26.01          0.0       organic   

       year            region  
0      2015            Albany  
1      2015            Albany  
2      2015            Albany  
3      2015            Albany  
4      2015            Albany  
...     ...               ...  
18244  2018  WestTexNewMexico  
18245  2018  WestTexNewMexico  
18246  2018  WestTexNewMexico  
18247  2018  WestTexNewMexico  
18248  2018  WestTexNewMexico  

[18249 rows x 14 columns]

7. Dari folder `data_tugas1` baca data `chinook.db` dengan `sqlite3`. Di dalam pandas ambil tabel kolom `Employeeid`,`LastName`,`Title` dari tabel `employees` dan tampilkan tabelnya. Simpan tabel kedalam `dataframe_3`, kemudian save kedalam `employees.json` dengan orientasi `columns`. 

In [27]:
### Tulis kode anda disini
import sqlite3
con = sqlite3.connect("data_tugas2/chinook.db")
dataframe_3 = pd.read_sql("SELECT Employeeid, LastName, Title FROM employees", con)
dataframe_3.to_json('employees.json', orient='columns')

**Soal Bonus**
8. Standardisasi merupakan teknik transformasi data yang sering digunakan. Transformasi ini mengubah distribusi data yang memiliki nilai $\mu$ dan standar deviasi $\sigma$ sehingga nilai $\mu = 0$ dan $\sigma = 1$. Formula dari standardisasi adalah:
$$z = \frac{x-\mu}{\sigma} $$

Diberikan array random dengan ukuran `10 x 3`. Lakukanlah standardisasi untuk tiap-tiap kolom dari array

In [28]:
np.random.seed(0)
x = np.random.random((10,3))
# your code here
x_standard = (x - np.mean(x, axis=0)) / np.std(x, axis=0)
print(x_standard)
print(x_standard.mean(0))
print(x_standard.std(0))

[[ 0.10485104  0.33623733  0.02196436]
 [ 0.09002614 -0.76457675  0.16637592]
 [-0.31468685  1.00300475  1.23033797]
 [-0.51892066  0.62523066 -0.22536411]
 [ 0.17738926  1.13072044 -1.75838021]
 [-1.63658987 -2.28792432  0.79157635]
 [ 0.96991792  0.9208373   1.28041268]
 [ 1.04913531 -0.62175385  0.61716488]
 [-1.5191126   0.05202934 -1.5162456 ]
 [ 1.5979903  -0.3938049  -0.60784223]]
[2.22044605e-17 4.38538095e-16 1.11022302e-16]
[1. 1. 1.]
